In [9]:
import numpy as np

In [63]:
def get_indices(N, n_batches, split_ratio):
    """Generates splits of indices from 0 to N-1 into uniformly distributed\
       batches. Each batch is defined by 3 indices [i, j, k] where\
       (j-i) = split_ratio*(k-j). The first batch starts with i = 0,\
       the last one ends with k = N - 1.
    Args:
        N (int): total counts
        n_batches (int): number of splits
        split_ratio (float): split ratio, defines position of j in [i, j, k].
    Returns:
        generator for batch indices [i, j, k]
    """

    if N < ((1 + (1 / split_ratio)) * n_batches) : return "Error bad data size"

    
    min_batch_size = int(1 + (1 / split_ratio))
    print(min_batch_size)

    for i in range (n_batches, 0, -1):
        if (min_batch_size * i) <= N // n_batches:
            test_size = min_batch_size * i
            print (i , test_size)
            step = test_size - ((N // n_batches - test_size) // i)
            break
    
    i = 0
    j = (test_size - int(test_size * split_ratio))
    k = test_size - 1 
    inds = np.array([i, j, k])
    yield inds
    
    for p in range(n_batches - 1):
        i += step
        j = i + (test_size - int(test_size * split_ratio) - 1)
        k = i + test_size - 1
        # todo: move forward batch
        # calculate new indices
        inds = (np.array([i, j , k]))
        yield inds

In [ ]:
N = input()
n_batches = input()
split_ratio = input()


In [64]:

for inds in get_indices(100, 5, 0.25):
    print(inds)
# expected result:
# [0, 44, 55]
# [11, 55, 66]
# [22, 66, 77]
# [33, 77, 88]
# [44, 88, 99]


5
4 20
[ 0 15 19]
[20 34 39]
[40 54 59]
[60 74 79]
[80 94 99]
